# Generated by Django 4.0.5 on 2022-06-16 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
